### ISSUE TITLE
mixed up column description in userprofile_latest table?

### ISSUE THREAD

**Issue by avanlinden** [Sage-Bionetworks/snowflake#59]
I was looking at the column comments describing the various table schemas in Snowflake (which are so so helpful to have!) and noticed the `ID` column on the `userprofile_latest` table is maybe inaccurately referring to the certified quiz table instead? I was operating on the assumption that this column was the Synapse user ID. Not urgent, just wanted to check!

https://github.com/Sage-Bionetworks/snowflake/blob/ac56ed26dcc5c4d894e6d29fffd71c56b731711a/synapse_data_warehouse/synapse/tables/V2.19.4__add_userprofile_latest_comments.sql#L9

**Comment by BryanFauble** [comment]
Thanks for the report @avanlinden I made an update and this will be fixed during the next change set run. I'll close this out for now.

**Comment by avanlinden** [comment]
Thanks team! Looks good.
